locale = "en"
label = "English"
title = "tocky.net"
copyright = "&copy; tocky.net"

[params.author]
    name = "Shin Tokiwa"
    image = "images/author.jpg"
    headline = "A developer who loves technology"
    bio = "CEO of ZEALOT Inc. Writing about the cloud, web development, and running a software company."
    links = [
        # { twitter = "https://twitter.com/tocky816" },
        # { instagram = "https://instagram.com/tocky" },
        # { facebook = "https://fb.com/tocky" },
        # { linkedin = "https://www.linkedin.com/in/tocky/" },
        { github = "https://github.com/tocky" },
    ]
