languageCode = "en"
languageName = "English"
displayName = "🇺🇸"
title = "tocky.net"

[author]
name = "Shin Tokiwa"
image = "images/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
    # { instagram = "https://instagram.com/tocky" },
    # { facebook = "https://fb.com/tocky" },
    # { linkedin = "https://www.linkedin.com/in/tocky/" },
    { github = "https://github.com/tocky" },
]
