title = "tocky.net (en)"

[author]
name = "Shin Tokiwa"
image = "images/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
    { twitter = "https://twitter.com/tocky816" }
]
