[[main]]
    name = "Blog"
    pageRef = "posts"
    weight = 10

[[main]]
    name = "Profile"
    pageRef = "profile"
    weight = 30

[[footer]]
    name = "Categories"
    pageRef = "categories"
    weight = 10

[[footer]]
    name = "Tags"
    pageRef = "tags"
    weight = 20
