[[main]]
    name = "Blog"
    pageRef = "posts"
    weight = 10

[[main]]
    name = "Topics"
    pageRef = "topics"
    weight = 20

[[footer]]
    name = "Privacy"
    url = "https://external-link"
