colorScheme = "slate"
defaultAppearance = "light"
enableSearch = true
enableCodeCopy = true

[header]
    logo = "images/evergreen.png"

[footer]
    showAppearanceSwitcher = true

[homepage]
    layout = "profile"

[article]
    showAuthor = false
    showBreadcrumbs = true
    showEdit = true
    showReadingTime = false
    showTableOfContents = true
    showTaxonomies = true
    showComments = true

[list]
    showBreadcrumbs = true
    showTableOfContents = true
    showTaxonomies = true
